id: A4BB1DFD2
title: Prayer for the Long Life Dodrupchen Rinpoche
type: translation
pechas:
- IF469EE4E
- ID93F6E74
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:57.921998
  last_modified_at: 2023-01-04 11:54:57.922012
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF469EE4E/7BDD: B440
  ID93F6E74/1DA0: B440
